// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPPJ2u9lYqyvHWbYMX7VWTtB8YOP2KC1E',
    appId: '1:522793023732:web:a4719dc8a6ecdd57d346a1',
    messagingSenderId: '522793023732',
    projectId: 'myexpenses-9915b',
    authDomain: 'myexpenses-9915b.firebaseapp.com',
    storageBucket: 'myexpenses-9915b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDELBGDJg7kc8_1uiJpKZwmn_VsUlcUAVk',
    appId: '1:522793023732:android:c46b469a583b5e58d346a1',
    messagingSenderId: '522793023732',
    projectId: 'myexpenses-9915b',
    storageBucket: 'myexpenses-9915b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC65dLF_vmz3olNyaLXlBVY-GOi-H59TDc',
    appId: '1:522793023732:ios:cb7e696de46174e0d346a1',
    messagingSenderId: '522793023732',
    projectId: 'myexpenses-9915b',
    storageBucket: 'myexpenses-9915b.appspot.com',
    iosBundleId: 'com.felipemagalhaes.myexpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC65dLF_vmz3olNyaLXlBVY-GOi-H59TDc',
    appId: '1:522793023732:ios:cb7e696de46174e0d346a1',
    messagingSenderId: '522793023732',
    projectId: 'myexpenses-9915b',
    storageBucket: 'myexpenses-9915b.appspot.com',
    iosBundleId: 'com.felipemagalhaes.myexpenses',
  );
}
